### ISSUE TITLE
can't The connection after the first connection

### ISSUE THREAD

**Issue by spz2020** [Erder00/royale-brawl-v29#11]
![Screenshot_2024-12-02-11-07-21-28_a6b00c61f9cae84563f9e49c6df08295](https://github.com/user-attachments/assets/958d8df5-12d8-4fa0-9f05-3a32433a8db5)
![Screenshot_2024-12-02-11-09-37-55_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/74b8085d-608d-4897-80c2-55fc63a6d4f5)

**Comment by Erder00** [comment]
check  the database

**Comment by spz2020** [comment]
> check the database

im check it and reinstall database

**Comment by spz2020** [comment]
I tried add new club And then it didn't work Then it was disconnected when I went back

**Comment by spz2020** [comment]
error cause?:cd813e79a764c4dde932e404c459f2f1d5372b9f

**Comment by Erder00** [comment]
i honestly don't feel very motivated to continue the project rn, maybe i'll look into it

**Comment by Erder00** [comment]
> error cause?:[4765923#diff-f53e104435f41349cc36993728d719eade017fea4c0f2f8658773002faaabf9f](https://github.com/Erder00/royale-brawl-v29/commit/4765923046c7c3898590e5c99584739ce9695252#diff-f53e104435f41349cc36993728d719eade017fea4c0f2f8658773002faaabf9f)

okay, i tried re connecting and using 2 clients at the same time. there was no such issue for me.
is there anything else i need to do to  recreate this issue?
what happens if you clear app data?

**Comment by Erder00** [comment]
> > error cause?:[4765923#diff-f53e104435f41349cc36993728d719eade017fea4c0f2f8658773002faaabf9f](https://github.com/Erder00/royale-brawl-v29/commit/4765923046c7c3898590e5c99584739ce9695252#diff-f53e104435f41349cc36993728d719eade017fea4c0f2f8658773002faaabf9f)
> 
> okay, i tried re connecting and using 2 clients at the same time. there was no such issue for me. is there anything else i need to do to recreate this issue? what happens if you clear app data?

might also have been caused by me breaking the apk, redownload and check again if the issue persists

**Comment by spz2020** [comment]
> > error cause?:[4765923#diff-f53e104435f41349cc36993728d719eade017fea4c0f2f8658773002faaabf9f](https://github.com/Erder00/royale-brawl-v29/commit/4765923046c7c3898590e5c99584739ce9695252#diff-f53e104435f41349cc36993728d719eade017fea4c0f2f8658773002faaabf9f)
> 
> okay, i tried re connecting and using 2 clients at the same time. there was no such issue for me. is there anything else i need to do to recreate this issue? what happens if you clear app data?

1: create club
2: Wait a minute
2: disconnected

**Comment by Erder00** [comment]
rewrote some stuff, could you check if that fixed it?

**Comment by spz2020** [comment]
![Screenshot_2024-12-08-09-47-32-74_10e1159e11da580d875d4492eeab983c](https://github.com/user-attachments/assets/c9a3a87a-b36d-448e-b5cb-bde7acb8feaa)
