### ISSUE TITLE
[Feature request] ChampionShip challenges

### ISSUE THREAD

**Issue by spz2020** [Erder00/royale-brawl-v29#14]

**Comment by Erder00** [comment]
how do you imagine that being done? i think i don't get the idea. isn't the brawlstars championship mostly done outside of the  game?

**Comment by spz2020** [comment]
oops Wrong name

**Comment by Erder00** [comment]
oh, makes sense yeah

**Comment by Erder00** [comment]
i thought about it, it seems kind of useless to me compared to the works that i'd have to put in. will close this but keep it in the back of my mind. ty still
