### ISSUE TITLE
client crashing at 100%

### ISSUE THREAD

**Issue by Zordon1337** [Erder00/royale-brawl-v29#2]
Not sure what have i did wrong but client connects to server, but the problem is that it crashes on 100%. not sure but maybe fact that i changed server port to other because i already use 9339 port has something to do with this

**Comment by Erder00** [comment]
wasn't able to replicate the issue by changing the port, what device are you testing on? also, i'm rewriting the script (hopefully) tomorrow

**Comment by Zordon1337** [comment]
maybe my config is messed up

**Comment by Zordon1337** [comment]
nvrmind there is nothing that i could mess up actually

**Comment by Zordon1337** [comment]
okay, so it seems issue fixed itself? idk i just restarted server and now it works. sorry for wasting your time

**Comment by Erder00** [comment]
dw, it happens. ty for making a bug report
