### ISSUE TITLE
discord docs

### ISSUE THREAD

**Issue by Erder00** [Erder00/royale-brawl-v29#20]
add docs for discord dev portal to create the dc bot
(i fucking hate documentation)

**Comment by SANS3R66** [comment]
https://www.google.com/search?q=how+to+create+a+bot+in+discord

**Comment by Erder00** [comment]
> https://www.google.com/search?q=how+to+create+a+bot+in+discord

people don't know how to use google apparently

**Comment by Erder00** [comment]
yeah, fuck this. i'm too lazy and google exists
