### ISSUE TITLE
how to change message in lobby with name Royale Brawl v29

### ISSUE THREAD

**Issue by luvriik** [Erder00/royale-brawl-v29#23]
how to change message in lobby with name Royale Brawl v29 and ur github

**Comment by luvriik** [comment]
and how to change color name to rainbow?

**Comment by Erder00** [comment]
> how to change message in lobby with name Royale Brawl v29 and ur github

messagemanager.cs


> and how to change color name to rainbow?

change name through db, not from ingame

**Comment by luvriik** [comment]
i change lobbydata and nothing changed...

**Comment by luvriik** [comment]
and idk how to login to db

**Comment by luvriik** [comment]
> i change lobbydata and nothing changed...

I miss recompile
i solve it
