### ISSUE TITLE
where change in db colro?

### ISSUE THREAD

**Issue by luvriik** [Erder00/royale-brawl-v29#26]
where change in db colro?

**Comment by Erder00** [comment]
just change the players name

**Comment by luvriik** [comment]
> just change the players name

`"Name":"<cff3200>D<cff6500>e<cff9800>v<cffcb00>e<cffff00>l<cffff00>o<cccff00>p<c99ff00>e<c66ff00>r</c>","NameSetByUser":false,`
??

**Comment by Erder00** [comment]
> > just change the players name
> 
> `"Name":"<cff3200>D<cff6500>e<cff9800>v<cffcb00>e<cffff00>l<cffff00>o<cccff00>p<c99ff00>e<c66ff00>r</c>","NameSetByUser":false,` ??

correct, but you should do "NameSetByUser":true,

**Comment by luvriik** [comment]
> `"Name":"<cff3200>D<cff6500>e<cff9800>v<cffcb00>e<cffff00>l<cffff00>o<cccff00>p<c99ff00>e<c66ff00>r</c>","NameSetByUser":false,`
> ??

Nothing changed
