### ISSUE TITLE
can't get colette

### ISSUE THREAD

**Issue by spz2020** [Erder00/royale-brawl-v29#4]

**Comment by Erder00** [comment]
ty for reporting, will look into it

**Comment by Erder00** [comment]
colette? i don't even have colette as an unlockable brawler. tried unlocking all, but surge didn't automatically unlock, could unlock him via boxes

**Comment by spz2020** [comment]
get colette in Brawl Pass it will give me surge

**Comment by spz2020** [comment]
and Patcher to make mod?

**Comment by Erder00** [comment]
> and you Will it be added Patcher to make mod?

what do you mean?

**Comment by spz2020** [comment]
Content Updater

**Comment by Erder00** [comment]
> Content Updater

It's already a feature, the assets directory has the files

**Comment by Erder00** [comment]
should be kind of fixed, looks fine server side. but i think there's something wrong client side still so i will keep this open

**Comment by Erder00** [comment]
fixed in 273532a and efd4515
