### ISSUE TITLE
suggestion: rewrite blyat

### ISSUE THREAD

**Issue by SANS3R66** [Erder00/royale-brawl-v29#9]
рояль бравл - это говно ебаное, в котором 1 метод это wrapper другого метода, который, в свою очередь wrapper еще одного метода.
и еще там пиздец дохуя говнокода собачего поэтому лучше переписывай все к чертям

**Comment by Erder00** [comment]
> рояль бравл - это говно ебаное, в котором 1 метод это wrapper другого метода, который, в свою очередь wrapper еще одного метода.
> и еще там пиздец дохуя говнокода собачего поэтому лучше переписывай все к чертям

I will rewrite everything in holy C, thank you for the great suggestion
